steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- script: |
    allure generate --clean
    allure report generate --report-dir $(Build.ArtifactStagingDirectory)/allure-report
  displayName: 'Generate Allure report'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/allure-report'
    artifactName: 'AllureReports'
    publishLocation: 'Container'
